-- CreateEnum
CREATE TYPE "ClientPlan" AS ENUM ('START', 'MASTER', 'PREMIUM', 'CUSTOM');

-- CreateEnum
CREATE TYPE "ClientStatus" AS ENUM ('ACTIVE', 'PAUSED', 'CANCELLED');

-- AlterTable
ALTER TABLE "ClientProfile"
  ADD COLUMN IF NOT EXISTS "cpfCnpj" TEXT,
  ADD COLUMN IF NOT EXISTS "address" TEXT,
  ADD COLUMN IF NOT EXISTS "plan" "ClientPlan" NOT NULL DEFAULT 'START',
  ADD COLUMN IF NOT EXISTS "customPlanDescription" TEXT,
  ADD COLUMN IF NOT EXISTS "monthlyValue" DECIMAL(65,30),
  ADD COLUMN IF NOT EXISTS "contractMonths" INTEGER,
  ADD COLUMN IF NOT EXISTS "dueDate" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "clientStatus" "ClientStatus" NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN IF NOT EXISTS "statusReason" TEXT,
  ADD COLUMN IF NOT EXISTS "activeSince" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "deactivatedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "logoUrls" TEXT[] DEFAULT ARRAY[]::TEXT[];
